IF OBJECT_ID('USER_MASTER') IS NOT NULL
	DROP TABLE USER_MASTER
GO
CREATE TABLE USER_MASTER
(
	USER_ID		INT,
	PASSWORD	VARCHAR(50),
	EMAIL_ID	VARCHAR(20),
	MOBILE_NUMBER VARCHAR(10),
	ACTIVE		  CHAR(1),
	MODIFIED_BY	VARCHAR(20),
	MODIFIED_ON	DATETIME,
	CONSTRAINT PK_USER_MASTER PRIMARY KEY(USER_ID)
);


IF OBJECT_ID('DBO.SIGNUPUSER') IS NOT NULL
	DROP PROCEDURE DBO.SIGNUPUSER
GO
CREATE PROCEDURE DBO.SIGNUPUSER
(
	@EMAIL_ID		VARCHAR(50),
	@PASSWORD		VARCHAR(20),
	@MOBILE_NUMBER	VARCHAR(20),
	@FLAG			VARCHAR(200) OUTPUT
)
AS 
BEGIN
	DECLARE @USER_ID INT;
	DECLARE @XRECOUNT INT;

	SET @XRECOUNT =(SELECT COUNT(*) FROM USER_MASTER
						WHERE (EMAIL_ID =@EMAIL_ID OR MOBILE_NUMBER = @MOBILE_NUMBER));
	
	IF @XRECOUNT > 0
	BEGIN

		SET @FLAG ='Your Mail Id or mobile number already register';
		return;
	
	END;
	BEGIN TRY
		BEGIN TRANSACTION
		IF @XRECOUNT = 0
		BEGIN
			SET @USER_ID =(SELECT ISNULL(MAX(USER_ID),0)+1 
								FROM USER_MASTER);
			INSERT INTO USER_MASTER (USER_ID,PASSWORD,EMAIL_ID,MOBILE_NUMBER,ACTIVE,MODIFIED_BY,MODIFIED_ON)
							  VALUES(@USER_ID,@PASSWORD,@EMAIL_ID,@MOBILE_NUMBER,'Y','SYSTEM',GETDATE());
				SET @FLAG = 'SUCCESS:SignUp';
		END;
		COMMIT;
	END TRY
	BEGIN CATCH
		ROLLBACK;
		SET @FLAG = 'ERROR '+ERROR_MESSAGE();
	END CATCH;

END;
GO



IF OBJECT_ID ('DBO.LOGINUSER') IS NOT NULL
	DROP PROCEDURE DBO.LOGINUSER
GO
CREATE PROCEDURE DBO.LOGINUSER
(
	@EMAIL_ID		VARCHAR(50),
	@MOBILE_NUMBER	VARCHAR(10),
	@PASSWORD		VARCHAR(50)
)
AS
BEGIN
	DECLARE  @XSQL	 NVARCHAR(4000);

	SELECT	@XSQL = 'SELECT USER_ID,PASSWORD,EMAIL_ID,MOBILE_NUMBER,ACTIVE,MODIFIED_BY,MODIFIED_ON
									FROM USER_MASTER
									WHERE 1=1';
			IF @EMAIL_ID !=''
				 SELECT	@XSQL = @XSQL + ' AND EMAIL_ID = '''+@EMAIL_ID+'''';

			IF @MOBILE_NUMBER !=''
				SELECT	@XSQL = @XSQL + ' AND MOBILE_NUMBER = '''+@MOBILE_NUMBER+'''';

			IF @PASSWORD !=''
				SELECT @XSQL = @XSQL +' AND PASSWORD ='''+@PASSWORD+'''';

		EXEC sp_Executesql @XSQL;

END;
